[build]
publish = "public"
command = "npm run build"

[build.environment]
PREVIEW_MODE = 'false'

[context.staging.environment]
PREVIEW_MODE = 'true'

[context.branch-deploy]
command = "npm run noIndex"

[[plugins]]
package = "netlify-plugin-gatsby-cache"
[[plugins]]
package = "@netlify/plugin-sitemap"