[build]
publish = "public"
command = "npm run build"
environment = {PREVIEW_MODE = "false"}

[context.branch-deploy.environment]
PREVIEW_MODE = "true"

[[plugins]]
package = "netlify-plugin-gatsby-cache"
[[plugins]]
package = "@netlify/plugin-sitemap"