[build]
publish = "public"
command = "npm run build"

[context.branch-deploy]
command = "PREVIEW_MODE=true npm run build"

[[plugins]]
package = "netlify-plugin-gatsby-cache"
[[plugins]]
package = "@netlify/plugin-sitemap"