[build]
publish = "public"
command = "npm run build"

[build.environment]
PREVIEW_MODE = 'false'
GATSBY_CONCURRENT_DOWNLOAD = 15

[context.staging.environment]
PREVIEW_MODE = 'true'
command = "npm run noIndex"

[[plugins]]
package = "@netlify/plugin-sitemap"
[[plugins]]
package = "@netlify/plugin-gatsby"
