[build]
publish = "public"
command = "npm run build"

[build.environment]
PREVIEW_MODE = false

[context.staging]
publish = "public"
command = "npm run build"

[context.staging.environment]
PREVIEW_MODE = true

[[plugins]]
package = "netlify-plugin-gatsby-cache"
[[plugins]]
package = "@netlify/plugin-sitemap"