[build]
publish = "public"
command = "npm run build"

[context.staging]
publish = "public"
command = "npm run build"

[[plugins]]
package = "netlify-plugin-gatsby-cache"
[[plugins]]
package = "@netlify/plugin-sitemap"