const chapterList = [
	{ value: 'AL', label: 'Alabama' },
	{ value: 'AK', label: 'Alaska' },
	{ value: 'AZ', label: 'Arizona' },
	{ value: 'AR', label: 'Arkansas' },
	{ value: 'NY CR', label: 'Capital Region New York' },
	{ value: 'FL CEN', label: 'Central Florida' },
	{ value: 'NY CNY', label: 'Central New York' },
	{ value: 'TX CEN', label: 'Central Texas' },
	{ value: 'CA CE', label: 'Central Valley California' },
	{ value: 'CO', label: 'Colorado' },
	{ value: 'CT', label: 'Connecticut' },
	{ value: 'DE', label: 'Delaware' },
	{ value: 'PA ET', label: 'Eastern Pennsylvania' },
	{ value: 'FLPA', label: 'Florida Panhandle' },
	{ value: 'GA', label: 'Georgia' },
	{ value: 'KS', label: 'Greater Kansas' },
	{ value: 'CA LA', label: 'Greater Los Angeles and Central Coast' },
	{ value: 'PA PHI', label: 'Greater Philadelphia' },
	{ value: 'CA SAC', label: 'Greater Sacramento' },
	{ value: 'CA SF', label: 'Greater San Francisco Bay Area' },
	{ value: 'HI', label: 'Hawaii' },
	{ value: 'NY HW', label: 'Hudson Valley/Westchester' },
	{ value: 'ID', label: 'Idaho' },
	{ value: 'IL', label: 'Illinois' },
	{ value: 'IN', label: 'Indiana' },
	{ value: 'CA CV', label: 'Inland Empire and Desert Cities' },
	{ value: 'IA', label: 'Iowa' },
	{ value: 'KY', label: 'Kentucky' },
	{ value: 'LA', label: 'Louisiana' },
	{ value: 'ME', label: 'Maine' },
	{ value: 'MD', label: 'Maryland' },
	{ value: 'MA', label: 'Massachusetts' },
	{ value: 'MI', label: 'Michigan' },
	{ value: 'MN', label: 'Minnesota' },
	{ value: 'MS', label: 'Mississippi' },
	{ value: 'MO', label: 'Missouri' },
	{ value: 'MT', label: 'Montana' },
	{ value: 'DC', label: 'National Capital Area' },
	{ value: 'NE', label: 'Nebraska' },
	{ value: 'NV', label: 'Nevada' },
	{ value: 'NH', label: 'New Hampshire' },
	{ value: 'NJ', label: 'New Jersey' },
	{ value: 'NM', label: 'New Mexico' },
	{ value: 'NY NYC', label: 'New York City' },
	{ value: 'NY LI', label: 'New York Long Island' },
	{ value: 'NC', label: 'North Carolina' },
	{ value: 'ND', label: 'North Dakota' },
	{ value: 'FL FC', label: 'North Florida' },
	{ value: 'TX DAL', label: 'North Texas' },
	{ value: 'OH', label: 'Ohio' },
	{ value: 'OK', label: 'Oklahoma' },
	{ value: 'CA OC', label: 'Orange County' },
	{ value: 'OR', label: 'Oregon' },
	{ value: 'RI', label: 'Rhode Island' },
	{ value: 'CA SD', label: 'San Diego' },
	{ value: 'SC', label: 'South Carolina' },
	{ value: 'SC NY', label: 'South Central New York' },
	{ value: 'SD', label: 'South Dakota' },
	{ value: 'FL SE', label: 'Southeast Florida' },
	{ value: 'TX GH', label: 'Southeast Texas' },
	{ value: 'TX SC', label: 'South Texas' },
	{ value: 'FL SA', label: 'Southwest Florida' },
	{ value: 'FL TB', label: 'Tampa Bay' },
	{ value: 'TN', label: 'Tennessee' },
	{ value: 'UT', label: 'Utah' },
	{ value: 'VT', label: 'Vermont' },
	{ value: 'VA', label: 'Virginia' },
	{ value: 'WA', label: 'Washington' },
	{ value: 'NY WNY', label: 'Western New York' },
	{ value: 'PA PIT', label: 'Western Pennsylvania' },
	{ value: 'WV', label: 'West Virginia' },
	{ value: 'WI', label: 'Wisconsin' },
	{ value: 'WY', label: 'Wyoming' },
]

export default chapterList
