name: rollbar
on: push
jobs:
    track-deploy:
        steps:
            - name: Rollbar deploy
              uses: rollbar/github-deploy-action@2.0.0
              id: rollbar_deploy
              with:
                  environment: 'production'
                  version: ${{ github.sha }}
              env:
                  ROLLBAR_ACCESS_TOKEN: ${{ secrets.ROLLBAR_ACCESS_TOKEN }}
                  ROLLBAR_USERNAME: ${{ github.actor }}
